- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - vim
      - sshpass
      - python3
      - python-pip
      - mysql-client-5.7
      - tmux
      - docker
      - docker-compose
