- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{ item }}
    with_times:
      - vim
      - sshpass
      - python3
      - python2
      - python-pip
      - mysql-client-5.7
      - tmux
      - docker
      - docker-compose
      - golang-stable
